# Generated by Django 6.0 on 2025-12-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_guests', models.IntegerField(default=2)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
